[package]
name = "dupefiles"
version = "1.0.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
walkdir = "2.5.0"
anyhow = "1.0.91"
tempfile = "3.13.0"

[features]
debug = []


[lints]
rust = { unused_variables = "allow", unused_macros="allow" }