[package]
name = "dupefiles"
version = "1.0.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
walkdir = "2.4.0"
anyhow = "1.0.75"
tempfile = "3.2"

[features]
debug_loop = []


[lints]
rust = { dead_code = "allow" , unused_variables = "allow" }