[package]
name = "dupefiles"
version = "1.0.0"
edition = "2021"

[dependencies]
sha2 = "*"
walkdir = "*"
anyhow = "*"
tempfile = "*"

[features]
debug = []


#[lints]
#rust = { unused_variables = "allow", unused_macros="allow" }